export const industrias = [
  "Actividades Financieras, Bancarias y/o Bursátiles",
  "Acuerdos de Transmisión y Derechos de Televisión",
  "Bienes Raíces",
  "Contratación de Jugadores y Agentes",
  "Empresas de Entretenimiento",
  "Eventos y Actividades de Promoción",
  "Industria de Consumo",
  "Industria de la Construcción",
  "Industria del Deporte y Equipamiento Deportivo",
  "Industria del Juego",
  "Industria textil",
  "Medios y Entretenimiento",
  "Merchandising y Ventas de Productos Oficiales",
  "Otra",
  "Patrocinios y Acuerdos Comerciales",
  "Tareas Profesionales Juridicos, Fiscales, Auditoría y/o Consultoría",
  "Telecomunicaciones",
  "Uso de Plataformas Digitales y Redes Sociales",
  "Venta de Entradas a Eventos Deportivos",
  "Viajes y Hotelería",
] as const;
